# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-29 11:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='accont_balance',
            new_name='account_balance',
        ),
    ]
