# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-04 06:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20170129_1131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='loan_balance',
        ),
    ]
