# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-05 08:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_remove_customer_loan_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='ban',
            field=models.BooleanField(default=False),
        ),
    ]
