# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-18 09:48
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
        ('stockmarket', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=9, validators=[django.core.validators.MinValueValidator(0.0)])),
            ],
        ),
        migrations.CreateModel(
            name='ComplimentaryCompanies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factor', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('take_out_time', models.DateTimeField(auto_now_add=True)),
                ('repay_time', models.DateTimeField(blank=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='NewsImpact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('impact', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='SupplementaryCompanies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factor', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='NewsPublished',
        ),
        migrations.RemoveField(
            model_name='price',
            name='company',
        ),
        migrations.RemoveField(
            model_name='company',
            name='buy',
        ),
        migrations.RemoveField(
            model_name='company',
            name='sell',
        ),
        migrations.RemoveField(
            model_name='news',
            name='impact1',
        ),
        migrations.RemoveField(
            model_name='news',
            name='impact10',
        ),
        migrations.RemoveField(
            model_name='news',
            name='impact2',
        ),
        migrations.RemoveField(
            model_name='news',
            name='impact3',
        ),
        migrations.RemoveField(
            model_name='news',
            name='impact4',
        ),
        migrations.RemoveField(
            model_name='news',
            name='impact5',
        ),
        migrations.RemoveField(
            model_name='news',
            name='impact6',
        ),
        migrations.RemoveField(
            model_name='news',
            name='impact7',
        ),
        migrations.RemoveField(
            model_name='news',
            name='impact8',
        ),
        migrations.RemoveField(
            model_name='news',
            name='impact9',
        ),
        migrations.RemoveField(
            model_name='news',
            name='quick_iter',
        ),
        migrations.AddField(
            model_name='company',
            name='available_quantity',
            field=models.PositiveIntegerField(default=10000),
        ),
        migrations.AddField(
            model_name='company',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='total_quantity',
            field=models.PositiveIntegerField(default=10000),
        ),
        migrations.AddField(
            model_name='news',
            name='media',
            field=models.FileField(blank=True, max_length=200, null=True, upload_to=None),
        ),
        migrations.AlterField(
            model_name='company',
            name='stock_price',
            field=models.DecimalField(decimal_places=2, default=1000.0, max_digits=9, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='company',
            name='symbol',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_text',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='Price',
        ),
        migrations.AddField(
            model_name='supplementarycompanies',
            name='company1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplementary_company_1', to='stockmarket.Company'),
        ),
        migrations.AddField(
            model_name='supplementarycompanies',
            name='company2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplementary_company_2', to='stockmarket.Company'),
        ),
        migrations.AddField(
            model_name='newsimpact',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockmarket.Company'),
        ),
        migrations.AddField(
            model_name='newsimpact',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockmarket.News'),
        ),
        migrations.AddField(
            model_name='complimentarycompanies',
            name='company1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complimentary_company_1', to='stockmarket.Company'),
        ),
        migrations.AddField(
            model_name='complimentarycompanies',
            name='company2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complimentary_company_2', to='stockmarket.Company'),
        ),
        migrations.AddField(
            model_name='companyhistory',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockmarket.Company'),
        ),
    ]
