# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-18 10:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockmarket', '0002_auto_20170118_1518'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ComplimentaryCompanies',
            new_name='ComplimentaryCompany',
        ),
        migrations.RenameModel(
            old_name='SupplementaryCompanies',
            new_name='SupplementaryCompany',
        ),
    ]
