# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-20 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmarket', '0003_auto_20170118_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='news',
            name='published_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
