# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-29 12:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockmarket', '0004_auto_20170129_1131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='published_on',
            new_name='publish_on',
        ),
    ]
