# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-29 12:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockmarket', '0005_auto_20170129_1811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='publish_on',
        ),
    ]
