# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-29 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmarket', '0007_news_published_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='key',
            field=models.CharField(default=b'DeleteME', max_length=20),
        ),
        migrations.AddField(
            model_name='parameter',
            name='value',
            field=models.FloatField(default=0),
        ),
    ]
