# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-29 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmarket', '0008_auto_20170129_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='iterations_run',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
