# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-29 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmarket', '0009_news_iterations_run'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='iterations_run',
        ),
        migrations.AddField(
            model_name='newsimpact',
            name='iterations_run',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
