# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-02 20:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmarket', '0010_auto_20170129_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyhistory',
            name='stocks_available',
            field=models.PositiveIntegerField(default=10000),
        ),
    ]
