# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-02 22:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockmarket', '0011_companyhistory_stocks_available'),
        ('stockmarket', '0011_auto_20170203_0239'),
    ]

    operations = [
    ]
