# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-04 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmarket', '0013_auto_20170204_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='annual_growth_rate',
            field=models.TextField(default='0'),
        ),
        migrations.AddField(
            model_name='company',
            name='market_cap',
            field=models.TextField(default='0'),
        ),
    ]
