# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-04 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmarket', '0014_auto_20170205_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='annual_growth_rate',
            field=models.CharField(default='0%', max_length=35),
        ),
        migrations.AlterField(
            model_name='company',
            name='market_cap',
            field=models.CharField(default='0%', max_length=35),
        ),
    ]
