# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-06 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmarket', '0015_auto_20170205_0112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='media',
        ),
        migrations.AddField(
            model_name='news',
            name='youtube_src',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
